### ISSUE TITLE
NPE on click after go back to my screen.

### ISSUE THREAD

**Issue by colymore** [futuresimple/android-floating-action-button#118]
Hi, im getting a NullPointerException after enter in fragment with a ActionsMenu, with actions added by code, go to other fragment, go back again and click in it to expand.
This is the stacktrace..

"java.lang.NullPointerException
at android.view.View$3.get(View.java:18471)
at android.view.View$3.get(View.java:18463)
at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:492)
at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:459)
at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:503)
at android.animation.ValueAnimator.start(ValueAnimator.java:921)
at android.animation.ValueAnimator.start(ValueAnimator.java:931)
at android.animation.ObjectAnimator.start(ObjectAnimator.java:437)
at android.animation.AnimatorSet.start(AnimatorSet.java:532)
at floatingactionbutton.FloatingActionsMenu.expand(FloatingActionsMenu.java:491)
at floatingactionbutton.FloatingActionsMenu.toggle(FloatingActionsMenu.java:483)
at floatingactionbutton.FloatingActionsMenu$2.onClick(FloatingActionsMenu.java:166)
at android.view.View.performClick(View.java:4475)
at android.view.View$PerformClick.run(View.java:18786)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5419)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
at dalvik.system.NativeStart.main(Native Method)"

**Comment by chalup** [comment]
Which library version do you use?

**Comment by colymore** [comment]
1.6.0

**Comment by chalup** [comment]
The similar issue was fixed in #103 on current master. Can you try using the latest code?

**Comment by colymore** [comment]
1.6.0 is the last version, right?

**Comment by chalup** [comment]
Yeah, but there are some commits merged with master after 1.6.0 release. Clone this repo, change VERSION_NAME & VERSION_CODE:

```groovy
VERSION_NAME=1.6.0-SNAPSHOT
VERSION_CODE=10
```

Run `gradle clean installArch` from project root, and try using 1.6.0-SNAPSHOT in your project. You might also need to add local maven repo to your build.gradle.

```groovy
repositories {
  mavenLocal()
}
```

Let me know if this works.

**Comment by colymore** [comment]
Yeah it works. Why you dont push this to master and upload to maven central?

**Comment by chalup** [comment]
Pushed as 1.7.0. Sorry for the delay, I planned adding more features to this release, but then I had more pressing issues to handle.
