### ISSUE TITLE
NullPointerException with a simple button

### ISSUE THREAD

**Issue by vaurdan** [futuresimple/android-floating-action-button#220]
I'm having some struggle to create a simple FAB button and interact with him on the Activity. I've the following on my XML (which is rendering correctly):

```xml
(...)
            <com.getbase.floatingactionbutton.FloatingActionButton
                android:id="@+id/pink_icon"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                fab:fab_icon="@drawable/ic_action"
                fab:fab_colorNormal="@color/pink"
                fab:fab_colorPressed="@color/pink_pressed"
                android:layout_alignParentBottom="true"
                android:layout_centerHorizontal="true"
                android:layout_marginBottom="16dp"
                android:layout_alignParentEnd="true"
                android:layout_alignParentStart="false"
                android:layout_marginRight="16dp" />
(...)
```

And on my activity I've the following:
```java
        FloatingActionButton btn = (FloatingActionButton) findViewById(R.id.pink_icon);
        btn.setVisibility(View.INVISIBLE);
```

I did use the visibility just for testing purposes.

Without that code in the activity the button renders, but if I had that code, the app crashes with a NullPointerException:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getbase.floatingactionbutton.FloatingActionButton.setVisibility(int)' on a null object reference
            at pt.myapp.ui.MessagesActivity.onCreate(MessagesActivity.java:61)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Any idea what I'm doing wrong? What is the correct way to simply initialize an fab?

**Comment by vaurdan** [comment]
Oh stupid me! I was calling the `findViewById` before `setContentView`. Duh!

Closing.
