### ISSUE TITLE
Android Studio rendering issue

### ISSUE THREAD

**Issue by koustuvsinha** [futuresimple/android-floating-action-button#222]
Hi, when I am trying to use this FAB by following the samples, Android Studio fails to render the button and gives this error instead (truncated stack message) : 
```java
java.lang.AssertionError
	at android.content.res.BridgeResources.getDimension(BridgeResources.java:345)
	at com.getbase.floatingactionbutton.FloatingActionButton.getDimension(FloatingActionButton.java:205)
	at com.getbase.floatingactionbutton.FloatingActionButton.init(FloatingActionButton.java:86)
	at com.getbase.floatingactionbutton.FloatingActionButton.<init>(FloatingActionButton.java:66)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:413)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	at com.android.tools.idea.rendering.LayoutlibCallback.loadView(LayoutlibCallback.java:177)
```
which on inspection looks like it is failing to get the dimension of a component. Any help? I have tried cleaning and rebuilding yet it persists

**Comment by koustuvsinha** [comment]
Solved it. Apparently I was using [makovkastar's fab](https://github.com/makovkastar/FloatingActionButton) in another part of my app, and since this one extends it so some conflict might be rising.
