### ISSUE TITLE
Bug: NPE on init->updateBackground

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [futuresimple/android-floating-action-button#284]
on this code:
        LayerDrawable layerDrawable = new LayerDrawable(
                new Drawable[]{
                        getResources().getDrawable(mSize == SIZE_NORMAL ? R.drawable.fab_bg_normal : R.drawable.fab_bg_mini),
                        createFillDrawable(strokeWidth),
                        createOuterStrokeDrawable(strokeWidth),
                        getIconDrawable()
                });

relevant log:

Caused by java.lang.NullPointerException
       at android.graphics.drawable.LayerDrawable.(LayerDrawable.java)
       at android.graphics.drawable.LayerDrawable.(LayerDrawable.java)
       at com.getbase.floatingactionbutton.FloatingActionButton.updateBackground(FloatingActionButton.java:234)
       at com.getbase.floatingactionbutton.FloatingActionButton.init(FloatingActionButton.java:90)
       at com.getbase.floatingactionbutton.FloatingActionButton.(FloatingActionButton.java)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:587)

This occurs only on Android 4.0.4 , 4.1.2, 4.2.1

**Comment by AndroidDeveloperLB** [comment]
this was my fault. I was using a webp with transparency on these versions of Android, which isn't supported.
