### ISSUE TITLE
getting the following issue: E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

### ISSUE THREAD

**Issue by joseph-mctigue** [futuresimple/android-floating-action-button#329]
First and foremost, I'm a new guy to android... but working on changing that soon. :-)
My project builds successfully.
I'm using the following emulator:
  Nexus S 4.4: resolution 480x800 hdpi, API level: 17, Target- Android 4.2 (Google APIs), CPU/ABI: x86, 
  Size on Disk: 4 GB.
  My emulator configurations are:
     Camera:  Front & Back emulated.
     Network speed: full
     Latency: none
     Graphics: GLES2.0
     Multi Core CPU: 4
     RAM: 343 MB
     VM heap: 32 MB
     Internal Storage: 800  MB
     SD card: Studio Managed  100 MB
     Device Frame: Enabled
     Custom skin definition: nexus_s
     Enabled keyboard input

I'm running Android Studio 2.2.3
On my Windows 7 64bit laptop with an i7 core processor.

Here's the first issue I get from my AVD console:
libpng warning: iCCP: known incorrect sRGB profile
HAX is working and emulator runs in fast virt mode.
emulator: Listening for console connections on port: 5554
emulator: Serial number of this emulator (for ADB): emulator-5554
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android SDK Tools" checkbox
 - Click "OK"

Here's the other issues I get from my app console when I test my app on the emulator:
Client not ready yet..Connected to process 3945 on device Nexus_S_API_17 [emulator-5554]
E/Trace: error opening trace file: No such file or directory (2)

E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method com.android.tools.fd.runtime.MonkeyPatcher.monkeyPatchExistingResources

E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method com.android.tools.fd.runtime.MonkeyPatcher.pruneResourceCache

E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

followed by the app killer exception:
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.IllegalStateException: Could not execute method for android:onClick
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                      at android.view.View.performClick(View.java:4204)
                      at android.view.View$PerformClick.run(View.java:17355)
                      at android.os.Handler.handleCallback(Handler.java:725)
                      at android.os.Handler.dispatchMessage(Handler.java:92)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:5041)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                      at android.view.View.performClick(View.java:4204) 
                      at android.view.View$PerformClick.run(View.java:17355) 
                      at android.os.Handler.handleCallback(Handler.java:725) 
                      at android.os.Handler.dispatchMessage(Handler.java:92) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:5041) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.mctigue.joseph.businesscardorganizer/com.mctigue.joseph.businesscardorganizer.AddCardImageActivity}; have you declared this activity in your AndroidManifest.xml?
                      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1618)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1417)
                      at android.app.Activity.startActivityForResult(Activity.java:3370)
                      at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                      at android.app.Activity.startActivityForResult(Activity.java:3331)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                      at android.app.Activity.startActivity(Activity.java:3566)
                      at android.app.Activity.startActivity(Activity.java:3534)
                      at com.mctigue.joseph.organizer.MainActivity.startClicked(MainActivity.java:59)
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                      at android.view.View.performClick(View.java:4204) 
                      at android.view.View$PerformClick.run(View.java:17355) 
                      at android.os.Handler.handleCallback(Handler.java:725) 
                      at android.os.Handler.dispatchMessage(Handler.java:92) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:5041) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                      at dalvik.system.NativeStart.main(Native Method) 
I/Process: Sending signal. PID: 3945 SIG: 9
Application terminated.

Line 59 of my main activity is the following:
startActivity(new Intent(MainActivity.this, SecondActivity.class));

Any help which could enlighten me further would be appreciated.
let me know if you need anything further.
Thanks in advance.
Joe

**Comment by pruthvi247** [comment]
Hi ,Any update on this even am facing the same issue with api level 19 android v4.4
