### ISSUE TITLE
Changing visibility of button within a menu 

### ISSUE THREAD

**Issue by kyleparker** [futuresimple/android-floating-action-button#99]
I may be doing something wrong, but I'm running into an issue with setting the visibility of an action button within the expanding menu. 

Here's my scenario - my expanding menu allows the user to add various types of media (image, video, etc). If the user has a Galaxy Note, I want to enable the "sketching" option as a media type. However, if they don't have a Note, the sketching option is hidden, as it is no use.

In my XML layout, if it set the visibility="gone", the app crashes when the menu expands:

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setAlpha(float)' on a null object reference
            at android.view.View$3.setValue(View.java:19388)
            at android.view.View$3.setValue(View.java:19385)
            at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:1288)
            at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:952)
            at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
            at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
            at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
            at android.animation.ValueAnimator.start(ValueAnimator.java:959)
            at android.animation.ValueAnimator.start(ValueAnimator.java:969)
            at android.animation.ObjectAnimator.start(ObjectAnimator.java:829)
            at android.animation.AnimatorSet.start(AnimatorSet.java:572)
            at com.getbase.floatingactionbutton.FloatingActionsMenu.expand(FloatingActionsMenu.java:471)
            at com.getbase.floatingactionbutton.FloatingActionsMenu.toggle(FloatingActionsMenu.java:463)
            at com.getbase.floatingactionbutton.FloatingActionsMenu$2.onClick(FloatingActionsMenu.java:164)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

Removing this fixes everything. The only way I've found to remove an action from the menu is to use the 'setOnFloatingActionsMenuUpdateListener' and set the visibility in the 'onMenuExpanded' event.

Am I overlooking something easy?

Thanks for this library - it is a great addition to the community. Your efforts are appreciated!

**Comment by chalup** [comment]
Looks like a bug.

**Comment by Chainfire** [comment]
Seeing the same issue

**Comment by Dfmarulanda** [comment]
@str4d im trying with your repo but still same issue.

**Comment by str4d** [comment]
Interesting. Can you try building the sample app from my repo? I replicated the bug in there (both XML and in code), and my fix solved it locally.

If the sample app works but your app doesn't, then you should look at the sample app's `activity_main.xml` and `MainActivity.java` and try to figure out how your app is different.

If the sample app doesn't work, please post all info about what you are testing it on.

**Comment by chalup** [comment]
@kyleparker , @Dfmarulanda , @Chainfire let me know if the issue still happens on current master branch.
